CREATE TABLE "transactions" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_from_id BIGINT,
    account_to_id BIGINT,
    type varchar(10),
    currency_shortname varchar(3),
    sum numeric(10,2),
    expense_category BOOLEAN,
    datetime timestamptz
                            );

ALTER TABLE transactions
    ADD CONSTRAINT fk_account_from FOREIGN KEY (account_from_id) REFERENCES customers(id),
    ADD CONSTRAINT fk_account_to FOREIGN KEY (account_to_id) REFERENCES customers(id);
