CREATE TABLE "customer_limit" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_limit DOUBLE PRECISION NOT NULL,
    service_limit DOUBLE PRECISION NOT NULL,
    limit_date TIMESTAMPTZ,
    customer_id BIGINT,
    FOREIGN KEY (customer_id) REFERENCES "customers" (id)
);