CREATE TABLE "currency_exchange" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_currency VARCHAR(3) NOT NULL,
    second_currency VARCHAR(3) NOT NULL,
    rate DOUBLE PRECISION NOT NULL
                                 );
